backend:
  name: github
  repo: Tomakin/personal-portfolio
  branch: main
  base_url: https://buraktomakin.com.tr
  auth_endpoint: cms-auth/auth

local_backend: true

site_url: https://buraktomakin.com.tr
display_url: https://buraktomakin.com.tr
publish_mode: simple

media_folder: public/images/post
public_folder: /images/post

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "list", default: ["programming"] }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
